### ISSUE TITLE
Plant diease Symptoms and Treatment not loading

### ISSUE THREAD

**Issue by AbhinavChangil** [DevilStudio27/Plant-Disease-Detection-and-Solution#1]
Actually an error while clicking disease info is there ....it says file "data.json" not found

i also checked in assests there is no such file 

if you have that data.json file then please provide

**Comment by DevilStudio27** [comment]
Data.json file - it stored the list of Diseases with set of symptoms and management of avoid such disease, U can create or own and use in this project

Eg : 
{
    "plant_disease": [
        {
            "name": "apple scab",
            "symptoms": "Disease attacks both leaves and fruit.\n This fungal disease forms pale yellow or olive-green spots on the upper surface of leaves.\n Dark, velvety spots may appear on the lower surface.\n Severely infected leaves become twisted and puckered and may drop early in the summer.",
            "management": "Prevent the initiation of primary infection cycles by reducing the germination of ascospores.\n Fungicide applications may also be made later in the season to prevent infection of old leaves, which can help reduce the amount of primary inoculum for the following season."
        },
{.............},
{.............},
{.............},
]
}

**Comment by AbhinavChangil** [comment]
[like]  Abhinav reacted to your message:
________________________________
